from pathlib import Path

from lesson.create_lesson import create_lesson
from training_material.create_training_material import create_training_material
from user.create_user_token import create_user_token

description = """In this Python course, we will embark on a journey into the realm of functions, a core concept in programming and Python. Functions are vital tools that enable you to encapsulate a block of code and execute it with various inputs, promoting code reusability and modularity. Throughout this course, you will delve into the fundamentals of functions, understanding their syntax, purpose, and how they play a pivotal role in breaking down complex tasks into manageable components."""

if __name__ == '__main__':
    login, password = Path('credentials').read_text().splitlines()
    response = create_user_token(login, password)
    token = response.json()['token']
    del login, password, response
    lesson_name = 'Basic python: Operations - functions'
    response = create_lesson(token, lesson_name, description, generator_path=Path('generator.py'))
    del response
    response = create_training_material(token, lesson_name, 'Autogenerated', [], [50])
    pass
